# file: pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multi_robot_isaacsim"
version = "2025.10.22"


[tool.setuptools]
packages = [
    "robot",
]