[package]
name = "isaacsim_mcp_extension"
version = "0.2.1"
title = "Isaacsim MCP Server"
description = "MCP server extension for Isaac Sim to enable communication with Claude and other AI assistants"
category = "Robotics"
keywords = ["mcp", "server", "socket", "simulation", "robotics"]

[dependencies]
"omni.isaac.core" = {}
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}



# Main python module this extension provides, it will be publicly available as "import isaacsim_mcp_extension".
[[python.module]]
name = "isaacsim_mcp_extension"



[python.pipapi]


[settings]
server.socket = 8766
server.host = "localhost"
