# Isaacsim资产的位置
path_asset: "/home/cleanuser/isaacsim_assets/Assets/Isaac/4.5/"

# 场景的位置
world:
  name: small_city_available.usd # 要使用的场的名字,和 asset / user_usd_files.json对应
  path: Isaac/Environments/Grid/default_environment.usd  # 从name 和 path中二选一
  physics_dt: 0.01  # 物理仿真步长时间
  rendering_dt: 0.0333333333333333333333333333333
  stage_units_in_meters: 1
  backend: torch
  sim_params:
    use_gpu_pipeline: True
#    use_gpu_broadphase: True
#    enable_gpu_dynamics: True
#    enable_ccd: False
#    enable_stabilization: True
#    solver_type: 1
#    broadphase_type: GPU

simulation_app_config:
  renderer: "RaytracedLighting"
  headless: False # 是否关闭渲染界面
  anti_aliasing: 0

# 定义启动时需要启用的扩展列表
enabled_extensions:
  - "isaacsim.core.nodes"
  - "isaacsim.ros2.bridge"
  - "omni.kit.graph.editor.core"
  - "omni.graph.bundle.action"
  - "omni.kit.graph.delegate.modern"
  - "isaacsim.asset.gen.omap"
  - "omni.graph.window.action"

experience: "isaacsim.exp.base.zero_delay.kit"

# 渲染配置, 下面的配置可以降低资源消耗并减少渲染器错误
settings:
  "/rtx/ecoMode/enabled": False
  "/rtx/post/dlss/execMode": 0
  "/rtx-transient/dlssg/enabled": False
  "/rtx-transient/dldenoiser/enabled": False
  "/rtx/directLighting/enabled": False
  "/rtx/indirectDiffuse/enabled": False
  "/rtx/sceneDb/ambientLightIntensity": 3.0
  "/rtx/reflections/enabled": False
  "/rtx/translucency/enabled": False
  "/rtx/raytracing/subsurface/enabled": False
  "/rtx/caustics/enabled": False
  "/persistent/physics/numThreads": 0


# 栅格地图
#资源消耗小的地图
#map:
#  cell_size: 1
#  start_point: [ 0, 0, 0 ]  # 构建gridmap的起点, 要保证这里是没有障碍物的
#  min_bound: [ -10, -10, 0 ]
#  max_bound: [ 10, 10, 2 ]
#  occupied_cell: 100
#  free_cell: 0
#  unknown_cell: -1
# 资源消耗大的地图
map:
  cell_size: 0.5
  start_point: [ 0, 0, 0 ]  # 构建gridmap的起点, 要保证这里是没有障碍物的
  min_bound: [ -34, -10, 0 ]
  max_bound: [ 19, 32, 10 ]
  occupied_cell: 100
  free_cell: 0
  unknown_cell: -1

# 语义地图
dict_map_semantic:
  depot0: [ 5, 4, 0 ]
  depot1: [ 5, 3, 0 ]  # 这里的坐标可根据实际情况调整
  depot2: [ 5, 2, 0 ]  # 这里的坐标可根据实际情况调整
  depot3: [ 5, 1, 0 ]  # 这里的坐标可根据实际情况调整
  place1: [ -4.5, 11.4, 0 ]
  place2: [ 5.6, 11.4, 0 ]
  place3: [ -4.7, 22.5, 0 ]
  place4: [ 5, 6.5, 0 ]


# --- 日志配置 ---
logging:
  level: "INFO" # 层级关系: DEBUG (all message) > INFO > WARNING > ERROR > CRITICAL (breaking errors)
  file: "logs/app.log" # 相对于项目根目录，或使用绝对路径

# ROS相关
ros:
  node_enable:
    node_scene_monitor: False
    node_action_server_plan_execution: True
    node_time: True

frames:
  frame_id_global: "map"
  frame_id_base: "base_link"

# 命名空间配置 (用于多无人机仿真)
namespace: ["uav1", "uav2", "uav3"]

# 机器人ROS Topic配置 (只需要写topic名称，namespace会自动添加)
robot_topics:
  jetbot:
    cmd_vel: "cmd_vel"
    odom: "odom"
    camera: "camera"
  cf2x:
    cmd_vel: "cmd_vel"
    odom: "odom"
#    takeoff: "takeoff"
#    land: "land"
    camera: "camera"
  g1:
    cmd_vel: "cmd_vel"
    odom: "odom"
#    joint_states: "joint_states"
    camera: "camera"
  h1:
    cmd_vel: "cmd_vel"
    odom: "odom"
#    joint_states: "joint_states"
    camera: "camera"
  target:
    cmd_vel: "cmd_vel"
    odom: "odom"
