simulation_app_config:
  renderer: "RaytracedLighting"
  headless: False # 是否关闭渲染界面
  anti_aliasing: 0

# 定义启动时需要启用的扩展列表
enabled_extensions:
  - "isaacsim.ros2.bridge"
  - "omni.kit.graph.editor.core"
  - "omni.graph.bundle.action"
  - "omni.kit.graph.delegate.modern"
  - "isaacsim.asset.gen.omap"
  - "omni.graph.window.action"

experience: "isaacsim.exp.base.zero_delay.kit"

# 渲染配置, 下面的配置可以降低资源消耗
settings:
  "/rtx/ecoMode/enabled": False
  "/rtx/post/dlss/execMode": 0
  "/rtx-transient/dlssg/enabled": False
  "/rtx-transient/dldenoiser/enabled": False
  "/rtx/directLighting/enabled": False
  "/rtx/indirectDiffuse/enabled": False
  "/rtx/sceneDb/ambientLightIntensity": 3.0
  "/rtx/reflections/enabled": False
  "/rtx/translucency/enabled": False
  "/rtx/raytracing/subsurface/enabled": False
  "/rtx/caustics/enabled": False
  "/persistent/physics/numThreads": 0

# Isaacsim资产的位置
asset_path: "/home/ubuntu/isaacsim_assets/Assets/Isaac/4.5/"

# 场景的位置
world:
  name: small_city_available.usd # 要使用的场的名字,和 asset / user_usd_files.json对应
  physics_dt: 0.005  # 1 / 200
  path: Isaac/Environments/Grid/default_environment.usd  # 从name 和 path中二选一
  rendering_dt: 0.016666666666666666666666667
  stage_units_in_meters: 1


# 栅格地图
map:
  cell_size: 0.3
  start_point: [ 0, 0, 0 ]  # 构建gridmap的起点, 要保证这里是没有障碍物的
  min_bounds: [ -34, -10, 0 ]
  max_bounds: [ 19, 32, 10 ]
  occupied_cell: 1
  empty_cell: 0
  invisible_cell: -1 # also unknown cell

# 语义地图
map_semantic:
  depot0: [ 5, 4, 0 ]
  depot1: [ 5, 3, 0 ]  # 这里的坐标可根据实际情况调整
  depot2: [ 5, 2, 0 ]  # 这里的坐标可根据实际情况调整
  depot3: [ 5, 1, 0 ]  # 这里的坐标可根据实际情况调整
  place1: [ -4.5, 11.4, 0 ]
  place2: [ 5.6, 11.4, 0 ]
  place3: [ -4.7, 22.5, 0 ]
  place4: [ 5, 6.5, 0 ]


# --- 日志配置 ---
logging:
  level: "INFO" # 可选: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/app.log" # 相对于项目根目录，或使用绝对路径

# ROS相关
ros:
  node_enable:
    node_scene_monitor: False
    node_action_server_plan_execution: True
