cf2x:
  - id: 0
    name: "cf2x_0"
    position: [ 7, 4 , 0.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    cfg_dict_camera: {}

  - id: 1
    name: "cf2x_1"
    position: [ 7, 3 , 0.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    cfg_dict_camera: {}

jetbot:
  - id: 0
    name: Allen
    position: [ 5, 4, 0.035 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    cfg_dict_camera:
      front:
        use_existing_camera: True
        path_prim_relative_to_robot: "/chassis/rgb_camera/jetbot_camera"
        id: 0
        frequency: 30
        resolution: [1280, 720]
        enable_semantic_detection: True

  - id: 1
    name: Bob
    position: [ 5, 3, 0.035 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    cfg_dict_camera:
      front:
        use_existing_camera: True
        path_prim_relative_to_robot: "/chassis/rgb_camera/jetbot_camera"
        id: 0
        frequency: 30
        resolution: [ 1280, 720 ]
        enable_semantic_detection: True
#
#  - id: 2
#    name: Candy
#    position: [ 5, 2, 0.035 ]
#    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
#    cfg_dict_camera:
#      front:
#        use_existing_camera: True
#        path_prim_relative_to_robot: "/chassis/rgb_camera/jetbot_camera"
#        id: 0
#        frequency: 30
#        resolution: [ 1280, 720 ]
#        enable_semantic_detection: True
#
#  - id: 3
#    name: David
#    position: [ 5, 1, 0.035 ]
#    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
#    cfg_dict_camera:
#      front:
#        use_existing_camera: True
#        path_prim_relative_to_robot: "/chassis/rgb_camera/jetbot_camera"
#        id: 0
#        frequency: 30
#        resolution: [ 1280, 720 ]
#        enable_semantic_detection: True

target:
  - id: 0
    name: 11g
    position: [ 5, 1, 0.035 ]
    quat: [1.0, 0.0, 0.0, 0.0]
    cfg_dict_camera:
      front:
        use_existing_camera: True
        path_prim_relative_to_robot: "/chassis/rgb_camera/jetbot_camera"
        id: 0
        frequency: 30
        resolution: [ 1280, 720 ]
        enable_semantic_detection: True


h1:
  - id: 0
    name: Hellen
    position: [ 3, 2, 1.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    cfg_dict_camera:
      front:
        use_existing_camera: False
        path_prim_relative_to_robot: "/d435_rgb_module_link"
        id: 0
        frequency: 30
        focal_length: 2
        orientation: [0.3827, -0.9239, 0.0000, 0.0000]
        resolution: [1280, 720]
        enable_semantic_detection: True
