cf2x:
  - id: 0
    position: [ 7, 4 , 0.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    disable_gravity: True
    use_simplified_controller: True

  - id: 1
    position: [ 7, 3 , 0.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    disable_gravity: True
    use_simplified_controller: True

jetbot:
  - id: 0
    position: [ 7, 5, 0.035 ]
    quat: [1, 0.0, 0.0, 0]
    disable_gravity: True
    use_simplified_controller: True

target:
  - id: 0
    position: [ 5, 1, 0.035 ]
    quat: [1.0, 0.0, 0.0, 0.0]
    disable_gravity: True
    use_simplified_controller: True

h1:
  - id: 0
    position: [ 3, 2, 1.05 ]
    quat: [0.7071067811865476, 0.0, 0.0, 0.7071067811865475]
    disable_gravity: True
    use_simplified_controller: True