[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "scene generation"
description = "use llm agent to generate scene"
authors = ["Lingchao Nie"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}

[[python.module]]
name = "scene_generation_python"